services:
  - type: web
    name: nimsa-ga-2025
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn nimsa_ga_2025.wsgi:application
